### ISSUE TITLE
Can not make under xen 4.11

### ISSUE THREAD

**Issue by labrenz** [razvan-cojocaru/libbdvmi#2]
We use a 4.18 kernel with xen 4.11.
After bootstrap and configure completing successfully, the make call creates the following error:

> bdvmixeneventmanager.cpp: In member function ‘virtual bool bdvmi::XenEventManager::enableMsrEvents(unsigned int, bool&)’:
> bdvmixeneventmanager.cpp:187:57: error: too few arguments to function ‘int xc_monitor_mov_to_msr(xc_interface*, uint32_t, uint32_t, bool, bool)’
>    return ( xc_monitor_mov_to_msr( xci_, domain_, msr, 1 ) == 0 );
>                                                          ^
> In file included from ../include/bdvmi/xencache.h:23,
>                  from ../include/bdvmi/xendriver.h:27,
>                  from bdvmixeneventmanager.cpp:17:
> /usr/include/xenctrl.h:2043:5: note: declared here
>  int xc_monitor_mov_to_msr(xc_interface *xch, uint32_t domain_id, uint32_t msr,
>      ^~~~~~~~~~~~~~~~~~~~~
> bdvmixeneventmanager.cpp: In member function ‘virtual bool bdvmi::XenEventManager::disableMsrEvents(unsigned int, bool&)’:
> bdvmixeneventmanager.cpp:199:57: error: too few arguments to function ‘int xc_monitor_mov_to_msr(xc_interface*, uint32_t, uint32_t, bool, bool)’
>    return ( xc_monitor_mov_to_msr( xci_, domain_, msr, 0 ) == 0 );
>                                                          ^
> In file included from ../include/bdvmi/xencache.h:23,
>                  from ../include/bdvmi/xendriver.h:27,
>                  from bdvmixeneventmanager.cpp:17:
> /usr/include/xenctrl.h:2043:5: note: declared here
>  int xc_monitor_mov_to_msr(xc_interface *xch, uint32_t domain_id, uint32_t msr,
>      ^~~~~~~~~~~~~~~~~~~~~
> bdvmixeneventmanager.cpp: In member function ‘virtual void bdvmi::XenEventManager::waitForEvents()’:
> bdvmixeneventmanager.cpp:566:38: error: ‘struct vm_event_mov_to_msr’ has no member named ‘value’; did you mean ‘new_value’?
>                      req.u.mov_to_msr.value, action );
>                                       ^~~~~
>                                       new_value
> bdvmixeneventmanager.cpp:572:26: error: ‘struct vm_event_mov_to_msr’ has no member named ‘value’; did you mean ‘new_value’?
>          req.u.mov_to_msr.value;
>                           ^~~~~
>                           new_value
>

**Comment by razvan-cojocaru** [comment]
Right, libbdvmi is a bit behind now. I'll try to sync the internal version with the public version soon.

**Comment by razvan-cojocaru** [comment]
Done, the GitHub version of the library is now in sync with the internal one. You should be able to use Xen 4.11 (or 4.12-unstable, for that matter) with it.
