### ISSUE TITLE
g++: error: unrecognized command line option '-std=gnu++14'

### ISSUE THREAD

**Issue by rushikeshjadhav** [razvan-cojocaru/libbdvmi#3]
```
# make
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I../include   -I/include  -W -Wall -std=gnu++14 -DXC_WANT_COMPAT_MAP_FOREIGN_API -DXC_WANT_COMPAT_EVTCHN_API -DXC_WANT_COMPAT_DEVICEMODEL_API -MT backendfactory.lo -MD -MP -MF .deps/backendfactory.Tpo -c -o backendfactory.lo backendfactory.cpp

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../include -I/include -W -Wall -std=gnu++14 -DXC_WANT_COMPAT_MAP_FOREIGN_API -DXC_WANT_COMPAT_EVTCHN_API -DXC_WANT_COMPAT_DEVICEMODEL_API -MT backendfactory.lo -MD -MP -MF .deps/backendfactory.Tpo -c backendfactory.cpp 
g++: error: unrecognized command line option '-std=gnu++14'
```
configure state does not detect gnu++14 compatibility.

**Comment by vilie** [comment]
You need to upgrade gcc. What version do you have?

**Comment by razvan-cojocaru** [comment]
I believe he wants the `configure` script to check if the compiler supports C++14 and bail if it doesn't.
It can be done in theory - I'll look into it whenever I can get a free moment - but it still won't help much, because libbdvmi requires at least C++14 and won't compile without said support anyway.

**Comment by razvan-cojocaru** [comment]
Fixed with Petre's PR: https://github.com/bitdefender/libbdvmi/pull/4

**Comment by rushikeshjadhav** [comment]
> You need to upgrade gcc. What version do you have?

I had 4.8.5 and figured that I'd need to upgrade.. Thanks for fixing it in compile itself. Feeling positive to work further on this :)
